// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: api/v1/service.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AitrailblazerServiceClient is the client API for AitrailblazerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AitrailblazerServiceClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type aitrailblazerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAitrailblazerServiceClient(cc grpc.ClientConnInterface) AitrailblazerServiceClient {
	return &aitrailblazerServiceClient{cc}
}

func (c *aitrailblazerServiceClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/aitrailblazer.service.v1.AitrailblazerService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AitrailblazerServiceServer is the server API for AitrailblazerService service.
// All implementations must embed UnimplementedAitrailblazerServiceServer
// for forward compatibility
type AitrailblazerServiceServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	mustEmbedUnimplementedAitrailblazerServiceServer()
}

// UnimplementedAitrailblazerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAitrailblazerServiceServer struct {
}

func (UnimplementedAitrailblazerServiceServer) Echo(context.Context, *StringMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedAitrailblazerServiceServer) mustEmbedUnimplementedAitrailblazerServiceServer() {}

// UnsafeAitrailblazerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AitrailblazerServiceServer will
// result in compilation errors.
type UnsafeAitrailblazerServiceServer interface {
	mustEmbedUnimplementedAitrailblazerServiceServer()
}

func RegisterAitrailblazerServiceServer(s grpc.ServiceRegistrar, srv AitrailblazerServiceServer) {
	s.RegisterService(&AitrailblazerService_ServiceDesc, srv)
}

func _AitrailblazerService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AitrailblazerServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aitrailblazer.service.v1.AitrailblazerService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AitrailblazerServiceServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// AitrailblazerService_ServiceDesc is the grpc.ServiceDesc for AitrailblazerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AitrailblazerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aitrailblazer.service.v1.AitrailblazerService",
	HandlerType: (*AitrailblazerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _AitrailblazerService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/service.proto",
}
