// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: api/v1/service.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AitrailblazerServiceClient is the client API for AitrailblazerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AitrailblazerServiceClient interface {
	SendPing(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	//	rpc GetBook(GetBookRequest) returns (Book) {
	//	  option (google.api.http) = {
	//	    get: "/v1/{name=publishers/*/books/*}"
	//	  };
	//	  option (google.api.method_signature) = "name";
	//	}
	//
	// Returns a specific bookstore shelf.
	GetShelf(ctx context.Context, in *GetShelfRequest, opts ...grpc.CallOption) (*Shelf, error)
}

type aitrailblazerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAitrailblazerServiceClient(cc grpc.ClientConnInterface) AitrailblazerServiceClient {
	return &aitrailblazerServiceClient{cc}
}

func (c *aitrailblazerServiceClient) SendPing(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/aitrailblazer.service.v1.AitrailblazerService/SendPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aitrailblazerServiceClient) GetShelf(ctx context.Context, in *GetShelfRequest, opts ...grpc.CallOption) (*Shelf, error) {
	out := new(Shelf)
	err := c.cc.Invoke(ctx, "/aitrailblazer.service.v1.AitrailblazerService/GetShelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AitrailblazerServiceServer is the server API for AitrailblazerService service.
// All implementations must embed UnimplementedAitrailblazerServiceServer
// for forward compatibility
type AitrailblazerServiceServer interface {
	SendPing(context.Context, *PingRequest) (*PingResponse, error)
	//	rpc GetBook(GetBookRequest) returns (Book) {
	//	  option (google.api.http) = {
	//	    get: "/v1/{name=publishers/*/books/*}"
	//	  };
	//	  option (google.api.method_signature) = "name";
	//	}
	//
	// Returns a specific bookstore shelf.
	GetShelf(context.Context, *GetShelfRequest) (*Shelf, error)
	mustEmbedUnimplementedAitrailblazerServiceServer()
}

// UnimplementedAitrailblazerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAitrailblazerServiceServer struct {
}

func (UnimplementedAitrailblazerServiceServer) SendPing(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPing not implemented")
}
func (UnimplementedAitrailblazerServiceServer) GetShelf(context.Context, *GetShelfRequest) (*Shelf, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShelf not implemented")
}
func (UnimplementedAitrailblazerServiceServer) mustEmbedUnimplementedAitrailblazerServiceServer() {}

// UnsafeAitrailblazerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AitrailblazerServiceServer will
// result in compilation errors.
type UnsafeAitrailblazerServiceServer interface {
	mustEmbedUnimplementedAitrailblazerServiceServer()
}

func RegisterAitrailblazerServiceServer(s grpc.ServiceRegistrar, srv AitrailblazerServiceServer) {
	s.RegisterService(&AitrailblazerService_ServiceDesc, srv)
}

func _AitrailblazerService_SendPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AitrailblazerServiceServer).SendPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aitrailblazer.service.v1.AitrailblazerService/SendPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AitrailblazerServiceServer).SendPing(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AitrailblazerService_GetShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AitrailblazerServiceServer).GetShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aitrailblazer.service.v1.AitrailblazerService/GetShelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AitrailblazerServiceServer).GetShelf(ctx, req.(*GetShelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AitrailblazerService_ServiceDesc is the grpc.ServiceDesc for AitrailblazerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AitrailblazerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aitrailblazer.service.v1.AitrailblazerService",
	HandlerType: (*AitrailblazerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPing",
			Handler:    _AitrailblazerService_SendPing_Handler,
		},
		{
			MethodName: "GetShelf",
			Handler:    _AitrailblazerService_GetShelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/service.proto",
}
